name: Deploy via ftp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Criar .env.production
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env.production
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env.production
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env.production
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env.production
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env.production
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env.production

      - name: Build
        run: npm run build

      - name: Deploy FTP Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }} 
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          # OBRIGATÓRIO: A pasta que o npm run build cria no seu Mac/GitHub
          localDir: "dist" 
          # ONDE VAI CAIR: Como seu servidor é Linux, public_html é o correto
          remoteDir: "public_html" 
          # DICA: Se o erro 530 persistir, tente adicionar:
          forceSsl: false