name: Deploy via ftp

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Criar .env.production
        run: |
          touch .env.production
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env.production
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env.production
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env.production
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env.production
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env.production
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env.production
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env.production
      - name: Instalar dependências
        run: npm ci

      - name: Validar código
        run: |
          npm run lint
          npm run test:run
          npm audit --omit=dev

      - name: Build
        run: |
          npm run build

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }} 
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"
          remoteDir: "public_html/st"
          forceSsl: false # Importante: manter false para evitar erro 530 na porta 21
